# Generated by Django 4.2.4 on 2023-08-31 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KOT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('staff_id', models.PositiveIntegerField()),
                ('out_time', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('in_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='KOTStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('close_time', models.DateTimeField()),
                ('open_time', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KOTMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('kot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kot.kot')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.item')),
            ],
        ),
        migrations.AddField(
            model_name='kot',
            name='order_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kot.orderchannel'),
        ),
        migrations.AddField(
            model_name='kot',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kot.kotstatus'),
        ),
    ]
