# Generated by Django 4.2.4 on 2023-08-31 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='KOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('staff_id', models.PositiveIntegerField()),
                ('kod_nemu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.item')),
                ('kod_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kod.status')),
            ],
        ),
    ]
